### ISSUE TITLE
Unsorted papers for stakeholders and faculty

### ISSUE THREAD

**Issue by AyushMann29** [Research-Nexas/Research-Nexas#1]
We can add categories filter to all 3 users to make it easy to navigate. Such as computer science, data science, physics, etc.

**Comment by Ajay-singh1** [comment]
@AyushMann29 If you want to open a PR regarding this go ahead

**Comment by Harshdev098** [comment]
Hi @AyushMann29  Please add some references(links,images,path to file,etc.), so that it can be easy to understand where you want to add that feature
