### ISSUE TITLE
FEAT : REVAMP FOOTER SECTION

### ISSUE THREAD

**Issue by AbhinaySngh** [Research-Nexas/Research-Nexas#11]
![image](https://github.com/user-attachments/assets/68a4397a-83eb-45fd-a4c6-e4d57c3eb76a)

**Comment by AbhinaySngh** [comment]
@Harshdev098 Please assign me this issue under gssoc-ext label.

**Comment by priyaahm** [comment]
I am willing to work on this issue. 

Please assign this to me and labels as gssoc extd and a level label.

**Comment by inkerton** [comment]
Hi !
I am currently working on this issue please assign it to me under gssoc extnd and hacktober fest

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/fdbf1d80-cf04-4900-bfd5-4f7bcb5af36d)
No file or directory named dbServer.js can you provide specific instructions on how can I run the project.

**Comment by Harshdev098** [comment]
You can find dbServer.js file in login-system folder. I have updated the Readme.md file, you can refer now

**Comment by harish08102004** [comment]
Hey @Harshdev098 if this issue is still open I can work on this.
