### ISSUE TITLE
Slider Section Layout Fix Needed

### ISSUE THREAD

**Issue by snehasharma200303** [Research-Nexas/Research-Nexas#164]
**Is your feature request related to a problem? Please describe.**

Some Section's images not properly visible it is cutting  and Images quality is very low not looking good .
The button in the slider section is not positioned correctly. It appears misaligned or outside of its intended position, which disrupts the user experience by making it difficult to interact with the button properly.
 Also This effect not looking good in between it has to be place on home section on background. 

**Describe the solution you'd like**
if position not change 

Images should be full visible and High resolution images should be used.
 
In Addition if Change the position i will fix at the background of home page with similar functionality and by fixing the issue i have raise.

**Additional context**

 Image cutting and  slide icon not on the position.

![{E83B04EC-017F-41D2-BF75-B1C5715481EA}](https://github.com/user-attachments/assets/1f0f9f51-876f-43ce-96fb-c70c97e1a60b)

**Comment by Harshdev098** [comment]
@snehasharma200303 you please add another images seeing the services and other section of the website

**Comment by Harshdev098** [comment]
@snehasharma200303 you please add another images seeing the services and other things

**Comment by Harshdev098** [comment]
Are you talking about the two issues ?

**Comment by snehasharma200303** [comment]
yes.. About slider section

**Comment by snehasharma200303** [comment]
Atleast you should be responsive for your behavior.. If there any problem occuring you can atleast tell but you not even responding..
