### ISSUE TITLE
Need to add icons for profile , home , about us , view results and log out for better exprerience

### ISSUE THREAD

**Issue by RaginiSharma01** [Research-Nexas/Research-Nexas#21]
#Profile Icon:
 "A circular icon representing a user, typically with a silhouette of a person's head and shoulders, to denote the profile section."
Example: This is where users can access their account details or settings.

#Home Icon:
: "An icon of a house, typically represented with a simple roof and door, symbolizing the home page or dashboard."
Example: This is where users can return to the main or landing page of the app.

#About Us Icon:
 "An icon that could be represented by an information (i) symbol, document, or speech bubble, indicating the About Us section."
Example: This leads users to information about the company, team, or project.

#View Results Icon:
"An icon with a magnifying glass or bar chart, representing the action of viewing results or statistics."
Example: This icon takes users to a page where they can see their test results, progress, or relevant data.

#Log Out Icon:
 "An icon often represented by an arrow coming out of a door or box, indicating the logout action."
Example: This allows users to safely exit their account from the platform.

i would like to work on this issue please assign me this task

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..
