### ISSUE TITLE
Add_Environment-Specific_Actions_for_Deployment_and_Testing

### ISSUE THREAD

**Issue by smog-root** [Research-Nexas/Research-Nexas#220]
**Tasks:**

**Real-Time Deployment Previews:**

- Implement actions to automatically create preview URLs for each pull request. This will allow reviewers to test the deployed version of the code without manually setting up the local environment.
- Suggested tools: Netlify
- Action: Netlify/netlify-action

**Multi-Environment Testing:**

- Set up actions to test the application across different environments, such as multiple versions of Node.js or browsers.
- Ensure compatibility for various setups (e.g., Node.js 14, 16, 18) and testing in different environments (e.g., Chrome, Firefox).
- Action: actions/setup-node for Node.js versions, actions/setup-chrome for browser testing

**Benefits:**

- Real-time feedback on how the code works in a deployed environment.
- Automated testing in multiple environments ensures compatibility and reduces bugs related to environment-specific issues.
- Faster review cycles and easier collaboration with non-technical stakeholders through preview deployments.

@Harshdev098

**Comment by smog-root** [comment]
@Harshdev098 i can add this! 
But every time a new PR is commited i should update the deploy!
which you can add to the repo discription!

i would be happy to maintain deployment for this repo!!

**Comment by smog-root** [comment]
@Harshdev098 can i get you'r discord?
or some social?

i need to give you the api key!!

**Comment by smog-root** [comment]
https://research-nexas.netlify.app/public

**Comment by smog-root** [comment]
@Harshdev098 reply bro??

i'm helping to really improve you'r repo! But you are not even replying!

i feel bad bro! 😞

**Comment by Harshdev098** [comment]
I was busy in reviewing the PRs
Just give me time

**Comment by Harshdev098** [comment]
Will see it don't worry

**Comment by Harshdev098** [comment]
Have you deployed the whole project?

**Comment by smog-root** [comment]
whats you'r discord?? @Harshdev098

**Comment by Harshdev098** [comment]
We can connect on LinkedIn

**Comment by smog-root** [comment]
https://linkedin.com/in/smogshashank

once text me on linkedin!

**Comment by smog-root** [comment]
![Screenshot (29)](https://github.com/user-attachments/assets/3482fbac-3adb-4f96-921e-5ff5c3302460)

just now update the repo!

**Comment by smog-root** [comment]
i have sent you a connect request!!
