### ISSUE TITLE
THE CHATBOT AND RETURN TO TOP BUTTON ARE COLLAPSING ON SAMLL SCREENS 

### ISSUE THREAD

**Issue by dnyanesh99borse** [Research-Nexas/Research-Nexas#239]
**### Is your feature request related to a problem? Please describe.**
On smaller screens, the chatbot and the "Return to Top" button are overlapping or collapsing into each other, causing usability issues. This results in a frustrating experience for users who might accidentally trigger one feature while trying to use the other. The lack of adequate spacing and positioning adjustments for mobile screens reduces the accessibility and effectiveness of both elements.

**### Describe the solution you'd like**
I would like the chatbot and "Return to Top" button to be repositioned and optimized for smaller screens. The solution should:

**### Ensure both elements are not overlapping or collapsing into one another.**
Use media queries to reposition the chatbot to a suitable area on the screen, such as the bottom left or right, while keeping it out of the way of the "Return to Top" button.
Maintain adequate spacing between the elements so that both are easily accessible.
Ensure that both the chatbot and the "Return to Top" button are responsive, resizing appropriately on smaller screens without impacting their usability.
**### Additional context**
For mobile-friendly design, Flexbox or absolute positioning can be used to maintain consistent spacing. Here’s an example screenshot showing how the elements overlap on smaller devices. Proper responsive adjustments for these features should enhance the user experience, especially on smartphones and tablets.
![image](https://github.com/user-attachments/assets/087c6707-997f-4a23-bac5-e7a41abd816e)
![image](https://github.com/user-attachments/assets/213d77a4-92a4-41cc-9ca4-f9578d2e699e)

**Comment by Pratikpawar13** [comment]
@Harshdev098 and my dear @dnyanesh99borse I will request to you please assign me this issue, I'll make sure I'll solve issue as early as possible with great efficiently .

**Comment by dnyanesh99borse** [comment]
yes sir no worry at all you can assign this issue to him too. glad to do @Harshdev098

**Comment by Harshdev098** [comment]
@dnyanesh99borse  Are you still working on it

**Comment by Sourabh782** [comment]
hey @Harshdev098 is this issue open? if so can i contribute to it??
