### ISSUE TITLE
Add navbar on other pages

### ISSUE THREAD

**Issue by Sudhanshu248** [Research-Nexas/Research-Nexas#255]
Currently on some pages there is no button to come back to home. Which creates problem for user to come on home page from other pages.

Hence, I would like to add navbar on all pages. So that user can switch pages easily.

![Screenshot 2024-10-20 225718](https://github.com/user-attachments/assets/e83d06aa-5991-4566-a314-3c43cf3f0379)

![Screenshot 2024-10-20 225753](https://github.com/user-attachments/assets/b3070a90-5773-4457-88fe-a26347f902d5)

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please assign me this issue under the label of hacktoberfest'24, hacktoberfest-accepted, level-2/3.

**Comment by Pratikpawar13** [comment]
@Harshdev098 Please assign me this issue, I'll solve this issue as early as possible.

**Comment by Sudhanshu248** [comment]
Sir, I am working on it. I will send you PR for this issue as soon as possible.
