### ISSUE TITLE
[⭐FEATURE] Add Feedback/Rate Us section ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Research-Nexas/Research-Nexas#290]
I want to add a Feedback/Rate section in footer.

@Harshdev098  PA please assign me this task.

![image](https://github.com/user-attachments/assets/dbfd3117-e1e0-46a1-8513-b6e5465ed3ad)

**Comment by Subhajit-2023-44** [comment]
@Harshdev098

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 please upgrade the level 2 to 3, If you check other projects, they are also giving level 3 for this..

Thank you

**Comment by Harshdev098** [comment]
Will upgrade it once you open a pr

**Comment by Subhajit-2023-44** [comment]
> Will upgrade it once you open a pr

okay, I will give PR soon
