### ISSUE TITLE
Add Correct footer on our contributors page.

### ISSUE THREAD

**Issue by Sudhanshu248** [Research-Nexas/Research-Nexas#293]
Currently on the our contributors page the footer is not matched with the other pages with website. Which makes that page different from website.

I would like to add same footer on our contributors page.

On our contributors page:

![Screenshot 2024-10-23 203456](https://github.com/user-attachments/assets/59a6166c-8f2b-4124-bd38-5990c1bd9b5c)

On other pages:

![Screenshot 2024-10-23 203910](https://github.com/user-attachments/assets/6cd689bc-5176-425b-a194-b0982b992ea0)

**Comment by Sudhanshu248** [comment]
@Harshdev098 Please assign me this issue under the label of hacktoberfest'24, hacktoberfest-accepted, level-2/3.

**Comment by RachitSahu26** [comment]
hey assign me this issue @Harshdev098  its taking to much time

**Comment by Avnee29** [comment]
Please assign me this issue under GSSoc'24 extd.
