### ISSUE TITLE
overlapping of icons.

### ISSUE THREAD

**Issue by agarwalbhargavi** [Research-Nexas/Research-Nexas#298]
<img width="958" alt="Screenshot 2024-10-23 222324" src="https://github.com/user-attachments/assets/4d1070cd-fbf9-4e6d-904c-c55cf024009c">
as seen on the right hand side down corner the scroll and bot icons are overlpping.
i would like work on this issue.
kindly asssign me this.
@Harshdev098

**Comment by Harshdev098** [comment]
#239  this issue is already created and someone is working on it. If he won't, will assign it to you no worry!

**Comment by agarwalbhargavi** [comment]
@Harshdev098 okay..pls feel free to assign anytime.

**Comment by agarwalbhargavi** [comment]
@Harshdev098 any update?
