### ISSUE TITLE
Improve Error Handling and Connection Management in `profile.js`

### ISSUE THREAD

**Issue by smog-root** [Research-Nexas/Research-Nexas#323]
Enhance the error handling, connection management, and query robustness in profile.js for improved reliability and maintainability.

**_Kindly add gssoc-ext with level and hacktoberfest-accepted labels! @Harshdev098!_**

**1. Error Handling in display Function:**

- Check if `result` is empty before accessing `result[0]` properties to avoid potential `undefined` errors.
- **Solution:** Add a check for an empty `result` and return a `404` Not Found response if no user data is found.

**2. Error Handling in `updateProfile`:**

- Wrap `db.query` in a promise to fully support asynchronous execution using `await`, improving compatibility with future refactoring.

**3. Token Logging:**

- Remove or mask sensitive information from any logging involving tokens, especially for production environments.

**4. Optimize SQL Query Syntax:**

- Consider switching from `INNER JOIN` to `LEFT JOIN` to include users without entries in `info_table`, if applicable.

**5. Connection Release in `display`:**

- Use a `try...finally` block to ensure `connection.release()` is called, even if an error occurs, preventing potential connection leaks.

**Comment by VijayBhandari2002** [comment]
i have good expertise in error handling, Can you please assign it to me.  So i can make a valuable contribution in your project
