### ISSUE TITLE
Adding chatbot to summarise research paper for stakeholder

### ISSUE THREAD

**Issue by AayushiJapsare15** [Research-Nexas/Research-Nexas#36]
Here at the view file section we can put a chatbot that will summarise , solve queries based on that research paper for the stakeholder. thus making it easier for them to evaluate and under them better.
![image](https://github.com/user-attachments/assets/0e550d22-f390-4570-af37-6761b419051f)

This is my chatbot which inputs a file, reads it , and solve queries based on that particular document.
![image](https://github.com/user-attachments/assets/cfcaa0d3-a74a-4247-b284-b6a503734d0c)

Having this feature in the system will really ease the work of stakeholder increasing their efficiency.

If you found this suggestion interesting @Harshdev098 I would to get it assigned to me.
Hope you do.

**Comment by Harshdev098** [comment]
Adding a chat bot is a good idea but it is useful only if it make the work easy for the stakeholders not queries,if you can add that type of feature it will be a great thing

**Comment by AayushiJapsare15** [comment]
what I meant by query is, the bot will be able to summarize specific contexts from the research paper itself while also being capable to address general questions.

**Comment by Harshdev098** [comment]
Okay, carry on with this

**Comment by AayushiJapsare15** [comment]
I have started working on it. 
And would like you to please add 'hacktoberfest-accepted' and 'level3' instead of 'label 3' label.

**Comment by Harshdev098** [comment]
I have already added level3 labels

**Comment by Harshdev098** [comment]
@AayushiJapsare15 Are you still working on it

**Comment by AayushiJapsare15** [comment]
yess
