### ISSUE TITLE
Add a hamburger for better responsivness

### ISSUE THREAD

**Issue by pallaviii21** [Research-Nexas/Research-Nexas#39]
Add a hamburger for small screen size , coz when the size is reduced the navbar elements are disarranging from their position.
that create a problem in resposivness of the webpage

https://github.com/user-attachments/assets/23dd7650-ae59-4152-85ef-415d38f05204

**Comment by Harshdev098** [comment]
@pallaviii21 Did you want to work on this issue, I can assign you. If you want this issue under hacktoberfest and gssoc please tell me. Will add the labels for the same

**Comment by pallaviii21** [comment]
Yes , I want to fix this problem
assign me @Harshdev098

**Comment by pallaviii21** [comment]
Please add GSSOC Levels too
