### ISSUE TITLE
Adding the Real-time Notifications 

### ISSUE THREAD

**Issue by Prajwalbandi13** [Research-Nexas/Research-Nexas#67]
The notifications feature will deliver instant updates to users about key activities happening on the platform. These notifications can appear as:

In-App Notifications: A notification bell icon in the header will show a badge with the number of new notifications. Users can click on the icon to view a dropdown list of recent updates.
Push Notifications (Optional): Implement browser-based push notifications using the Notification API and Service Workers, so users receive updates even when the app is not in focus.

**Comment by Shalinis19137** [comment]
on #77 problem I would like to contribute on this ,Please assign me this issue under gssoc - ext 2024

**Comment by Harshdev098** [comment]
Hey @Prajwalbandi13  Till yet you want to work on this issue
Please reply, unless I have to assign this issue @Shalinis19137

**Comment by Prajwalbandi13** [comment]
@Harshdev098 yes you can assign it to him

**Comment by Shalinis19137** [comment]
Thanks alot.
